### ISSUE TITLE
Manual configuration is automatically replaced (by discovery?)

### ISSUE THREAD

**Issue by rdvanbuuren** [MadMonkey87/HomeyCONZ#34]
**Describe the bug:**
Homey deCONZ app suddenly alters ip address. After that I can't connect to any of my devices.
I'm runnig deCONZ in a docker container and what I see is that, after some time, the ip address gets altered to the internal one of the docker container.

**How to reproduce:**
Steps to reproduce the behaviour:
1. Install deCONZ into Docker https://hub.docker.com/r/marthoc/deconz
2. Connect to deCONZ with Homey app
3. Enter ip address and ports. In my case this is 192.168.0.x or raspberrypi.local 
4. Test connection validity and save
5. After a while, open Homey deCONZ app again and go to configuration 
6. Ip address is altered to internal Docker ip (172.17.0.3 in my case)

**How it should work:**
Just keep the manual ip address / domain name that I've entered in the configuration.

**Additional context:**
It looks like this has something to do with the autodiscover function?

**Comment by richie80** [comment]
I have the same problem. My deconz is on a raspberry pi with home-assistant and deconz as an add on.

**Comment by MadMonkey87** [comment]
I think I know what is going on here. The app now features an "auto-repair connection" feature which will automatically attempt to repair the connection if it fails. This is targeted at dynamic ip's, for example your router might assign a different ip address to your deconz instance. I assume you have not setup your docker image with --net=host? This by default prevents that the discovery works correct! As already mentioned in the homey community this is not something that can be fixed in either the docker image or the app, by not setting this param you intentionally break the autodiscovery. 

To solve this there are two possible options:
 - disable this feature (see app config -> advanced)
 - use the --net=host parameter when setting uo the docker image

**Comment by richie80** [comment]
Unfortunately I don't see this option in Homey. 
There are only two possibilities: automatic config and manual config.

**Comment by MadMonkey87** [comment]
You are at the wrong place: 
![Screenshot_20201229-205831_Homey](https://user-images.githubusercontent.com/29612400/103310775-b027c900-4a18-11eb-96d9-e8bf2a7150c6.png)

**Comment by richie80** [comment]
I only see this:
Don’t have a top menu

[Image.jpeg]
________________________________
Van: Philippe Wechsler <notifications@github.com>
Verzonden: dinsdag, december 29, 2020 8:59 PM
Aan: MadMonkey87/HomeyCONZ
CC: richie80; Comment
Onderwerp: Re: [MadMonkey87/HomeyCONZ] Manual configuration is automatically replaced (by discovery?) (#34)


You are at the wrong place:
[Screenshot_20201229-205831_Homey]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F29612400%2F103310775-b027c900-4a18-11eb-96d9-e8bf2a7150c6.png&data=04%7C01%7C%7C63921968aadb47ce22ee08d8ac343dac%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637448687667965440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0S6hEp0MCU5UOdmVw2hFDE1oXcQhkPLbGMXLT3Yzc7c%3D&reserved=0>

**Comment by richie80** [comment]
![8335DC9C-F92D-4D17-A4D5-D9EE5E612D1B](https://user-images.githubusercontent.com/61156727/103315569-37c80480-4a26-11eb-821d-a92d24304ac6.jpeg)
